elastic_client_config:
  elastic_protocol: https
  elastichost: '3.228.218.39'
  elasticPrefix: ''
  elasticport: '9200'
  elasticUser: 'elastic'
  elasticIndex: 'sms'
  actions: []
  fileRecordCount: 160000
  fileCounter: 0
query_config:
  index: 'sms'
inbound_report_config:
  - calling_part_gt_operator: "Sky UK Limited"
    sale_rate: 0.02
  - calling_part_gt_operator: "Telefonica UK Limited"
    sale_rate: 0.022
  - calling_part_gt_operator: "Sky UK Limited"
    sale_rate: 0.02
  - calling_part_gt_operator: "Hutchison 3G UK Ltd"
    sale_rate: 0.016
  - calling_part_gt_operator: "Vodafone Limited"
    sale_rate: 0.022
  - calling_part_gt_operator: "EE Limited (Orange)"
    sale_rate: 0.02
outbound_report_config:
  - routing_index_bt: "EE_SK1"
    routing_index: 20
  - routing_index_bt: "EE_TC_SK1"
    routing_index: 21
  - routing_index_bt: "Hutchison 3G UK Ltd"
    routing_index: 21001
  - routing_index_bt: "Telefonica UK Limited"
    routing_index: 21002
  - routing_index_bt: "Sky UK Limited"
    routing_index: 21003
  - routing_index_bt: "Lycamobile (UK) Limited"
    routing_index: 21004
  - routing_index_bt: "EE Limited (TM)"
    routing_index: 21005
