elastic_client_config:
  elastic_protocol: https
  elastichost: '3.235.234.88'
  elasticPrefix: ''
  elasticport: '9200'
  elasticUser: 'elastic'
  elasticPassword: 'Z6YQxuHA=T_m3RCs8GlU'
  elasticIndex: 'sms'
  actions: []
  fileRecordCount: 160000
  fileCounter: 0
query_config:
  index: 'sms'