elastic_client_config:
  elastic_protocol: https
  elastichost: '3.226.239.99'
  elasticPrefix: ''
  elasticport: '9200'
  elasticUser: 'elastic'
  elasticPassword: 'l+G1pJ92zHpMza3lIYdB'
  elasticIndex: 'sms'
  actions: []
  fileRecordCount: 160000
  fileCounter: 0
query_config:
  index: 'sms'