elastic_client_config:
  elastic_protocol: https
  elastichost: '3.228.218.39'
  elasticPrefix: ''
  elasticport: '9200'
  elasticUser: 'elastic'
  elasticIndex: 'sms'
  actions: []
  fileRecordCount: 160000
  fileCounter: 0
query_config:
  index: 'sms'
inbound_report_config:
  sale_rate: .5
  calling_party_prefix: "*43*"
