elastic_client_config:
  elastic_protocol: https
  elastichost: '3.228.218.39'
  elasticPrefix: ''
  elasticport: '9200'
  elasticUser: 'elastic'
  elasticIndex: 'sms'
  actions: []
  fileRecordCount: 160000
  fileCounter: 0
query_config:
  index: 'sms'
inbound_report_config:
  - calling_part_gt_operator: "Sky UK Limited"
    sale_rate: 0.02
  - calling_part_gt_operator: "Telefonica UK Limited"
    sale_rate: 0.022
  - calling_part_gt_operator: "Sky UK Limited"
    sale_rate: 0.02
  - calling_part_gt_operator: "Hutchison 3G UK Ltd"
    sale_rate: 0.016
  - calling_part_gt_operator: "Vodafone Limited"
    sale_rate: 0.022
  - calling_part_gt_operator: "EE Limited (Orange)"
    sale_rate: 0.02
