elastic_client_config:
  elastic_protocol: https
  elastichost: '3.231.33.255'
  elasticPrefix: ''
  elasticport: '9200'
  elasticUser: 'elastic'
  elasticPassword: '3-ULKg6VMPWuZWUIymMo'
  elasticIndex: 'sms'
  actions: []
  fileRecordCount: 160000
  fileCounter: 0
query_config:
  index: 'sms'