elastic_client_config:
  elastic_protocol: https
  elastichost: '34.234.236.100'
  elasticPrefix: ''
  elasticport: '9200'
  elasticUser: 'elastic'
  elasticPassword: 'zj=w+MVqVV*FpkwDpf-v'
  elasticIndex: 'sms'
  actions: []
  fileRecordCount: 160000
  fileCounter: 0
query_config:
  index: 'sms'